<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net6.0</TargetFramework>
        <ImplicitUsings>disable</ImplicitUsings>
        <Nullable>disable</Nullable>
        <RootNamespace>Mrnchr.Balancery.Statistics.Benchmark</RootNamespace>
        
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="BenchmarkDotNet" Version="0.15.2" />
        <PackageReference Include="ClosedXML" Version="0.105.0" />
        <PackageReference Include="System.Data.SQLite" Version="1.0.119" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Balancery.Statistics.DataProvider\Balancery.Statistics.DataProvider.csproj" />
        <ProjectReference Include="..\Balancery.Statistics\Balancery.Statistics.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="obj\Release\net6.0\" />
    </ItemGroup>

</Project>
