<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <Nullable>disable</Nullable>
    </PropertyGroup>

    <Target Name="CopyOnPublish" AfterTargets="Publish">
        <MakeDir Directories="$(SolutionPath)\..\..\Balancery.Unity\Assets\Packages\"/>
        <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(SolutionPath)\..\..\Balancery.Unity\Assets\Packages\"/>
    </Target>

    <Target Name="CopyOnPublish" AfterTargets="Publish">
        <MakeDir Directories="$(SolutionPath)\..\..\Balancery.Unity\Assets\Artifacts\"/>
        <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(SolutionPath)\..\Artifacts\"/>
    </Target>

</Project>
