<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <Nullable>disable</Nullable>
        <RootNamespace>Mrnchr.Balancery.Statistics</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="ClosedXML" Version="0.105.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Balancery.Statistics.Shared\Balancery.Statistics.Shared.csproj" />
    </ItemGroup>

    <Target Name="CopyOnPublish" AfterTargets="Publish">
        <MakeDir Directories="$(SolutionPath)\..\..\Balancery.Unity\Assets\Packages\" />
        <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(SolutionPath)\..\..\Balancery.Unity\Assets\Packages\" />
    </Target>
    
</Project>
